services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $php2XliffSourceLang: '%markocupic_contao_php2xliff.sourceLanguage%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Markocupic\ContaoPhp2Xliff\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Writer}

    Markocupic\ContaoPhp2Xliff\String\XmlSanitizer:
        autowire: true
        autoconfigure: true
